name: Build and Notify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Cache Gradle and Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-maven-${{ hashFiles('**/*.gradle', '**/*.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-maven-

    - name: Build with Gradle
      run: ./gradlew clean build
